# Generated by Django 4.2.15 on 2025-01-21 09:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='point_of_contact_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='center_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, region=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='type_of_business',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
