# Generated by Django 4.2.15 on 2025-01-21 10:09

from django.db import migrations
import django.db.models.deletion
import zango.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=zango.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.customer'),
        ),
    ]
