# Generated by Django 4.2.15 on 2025-01-24 06:41

from django.db import migrations, models
import django.db.models.deletion
import zango.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_alter_customeraccount_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='customer',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='campaign',
            field=zango.apps.dynamic_models.fields.ZForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='risk_score',
            field=models.JSONField(default=dict),
        ),
    ]
