# Generated by Django 4.2.15 on 2025-01-24 12:58

from django.db import migrations
import django.db.models.deletion
import zango.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_remove_formsubmission_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='campaign',
            field=zango.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_models.campaign'),
        ),
    ]
