# Generated by Django 4.2.15 on 2025-01-24 13:05

from django.db import migrations
import django.db.models.deletion
import zango.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_alter_formsubmission_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='campaign',
            field=zango.apps.dynamic_models.fields.ZForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.campaign'),
            preserve_default=False,
        ),
    ]
