# Generated by Django 4.2.15 on 2025-01-27 15:16

from django.db import migrations
import zango.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_alter_formsubmission_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='associated_report',
            field=zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension]),
        ),
    ]
