# Generated by Django 4.2.15 on 2025-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0008_alter_formsubmission_associated_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='category_scores',
            field=models.JSONField(default=dict),
        ),
    ]
