# Generated by Django 4.2.15 on 2025-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0009_formsubmission_category_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='personal_details',
            field=models.JSONField(default=dict),
        ),
    ]
