# Generated by Django 4.2.15 on 2025-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0010_formsubmission_personal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='meta_details',
            field=models.JSONField(default=dict),
        ),
    ]
