# Generated by Django 4.2.15 on 2025-02-02 05:09

from django.db import migrations
import zango.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0011_formsubmission_meta_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='answers_report',
            field=zango.core.storage_utils.ZFileField(blank=True, null=True, upload_to=zango.core.storage_utils.RandomUniqueFileName, validators=[zango.core.storage_utils.validate_file_extension]),
        ),
    ]
