export const isHcpDashboard = window.location.pathname.includes(
	'/app/hcp/dashboard/'
);

export const HCP_MENU_ITEMS = [
	{ label: 'Profile', link: '/msdodtrack038/profile' },
];

export const STOCKIST_MENU_ITEMS = [
	{ label: 'Profile', link: '/msdodtrack038/profile' },
];

export const INITIATE_EYC_MENU_ITEMS = [];

export const SHOW_PROFILE_MENU_ITEMS = [];

export const nationalityOptions = [
	{ id: "India", label: "India" },
	{ id: "Afghan", label: "Afghan" },
	{ id: "Albanian", label: "Albanian" },
	{ id: "Algerian", label: "Algerian" },
	{ id: "American", label: "American" },
	{ id: "Andorran", label: "Andorran" },
	{ id: "Angolan", label: "Angolan" },
	{ id: "Antiguan", label: "Antiguan" },
	{ id: "Argentine", label: "Argentine" },
	{ id: "Armenian", label: "Armenian" },
	{ id: "Australian", label: "Australian" },
	{ id: "Austrian", label: "Austrian" },
	{ id: "Azerbaijani", label: "Azerbaijani" },
	{ id: "Bahamian", label: "Bahamian" },
	{ id: "Bahraini", label: "Bahraini" },
	{ id: "Bangladeshi", label: "Bangladeshi" },
	{ id: "Barbadian", label: "Barbadian" },
	{ id: "Belarusian", label: "Belarusian" },
	{ id: "Belgian", label: "Belgian" },
	{ id: "Belizean", label: "Belizean" },
	{ id: "Beninese", label: "Beninese" },
	{ id: "Bhutanese", label: "Bhutanese" },
	{ id: "Bolivian", label: "Bolivian" },
	{ id: "Bosnian", label: "Bosnian" },
	{ id: "Botswanan", label: "Botswanan" },
	{ id: "Brazilian", label: "Brazilian" },
	{ id: "British", label: "British" },
	{ id: "Bruneian", label: "Bruneian" },
	{ id: "Bulgarian", label: "Bulgarian" },
	{ id: "Burkinabe", label: "Burkinabe" },
	{ id: "Burmese", label: "Burmese" },
	{ id: "Burundian", label: "Burundian" },
	{ id: "Cambodian", label: "Cambodian" },
	{ id: "Cameroonian", label: "Cameroonian" },
	{ id: "Canadian", label: "Canadian" },
	{ id: "Cape Verdean", label: "Cape Verdean" },
	{ id: "Central African", label: "Central African" },
	{ id: "Chadian", label: "Chadian" },
	{ id: "Chilean", label: "Chilean" },
	{ id: "Chinese", label: "Chinese" },
	{ id: "Colombian", label: "Colombian" },
	{ id: "Comoran", label: "Comoran" },
	{ id: "Congolese", label: "Congolese" },
	{ id: "Costa Rican", label: "Costa Rican" },
	{ id: "Croatian", label: "Croatian" },
	{ id: "Cuban", label: "Cuban" },
	{ id: "Cypriot", label: "Cypriot" },
	{ id: "Czech", label: "Czech" },
	{ id: "Danish", label: "Danish" },
	{ id: "Djiboutian", label: "Djiboutian" },
	{ id: "Dominican", label: "Dominican" },
	{ id: "Dutch", label: "Dutch" },
	{ id: "East Timorese", label: "East Timorese" },
	{ id: "Ecuadorean", label: "Ecuadorean" },
	{ id: "Egyptian", label: "Egyptian" },
	{ id: "Emirati", label: "Emirati" },
	{ id: "Equatorial Guinean", label: "Equatorial Guinean" },
	{ id: "Eritrean", label: "Eritrean" },
	{ id: "Estonian", label: "Estonian" },
	{ id: "Ethiopian", label: "Ethiopian" },
	{ id: "Fijian", label: "Fijian" },
	{ id: "Filipino", label: "Filipino" },
	{ id: "Finnish", label: "Finnish" },
	{ id: "French", label: "French" },
	{ id: "Gabonese", label: "Gabonese" },
	{ id: "Gambian", label: "Gambian" },
	{ id: "Georgian", label: "Georgian" },
	{ id: "German", label: "German" },
	{ id: "Ghanaian", label: "Ghanaian" },
	{ id: "Greek", label: "Greek" },
	{ id: "Grenadian", label: "Grenadian" },
	{ id: "Guatemalan", label: "Guatemalan" },
	{ id: "Guinean", label: "Guinean" },
	{ id: "Guyanese", label: "Guyanese" },
	{ id: "Haitian", label: "Haitian" },
	{ id: "Honduran", label: "Honduran" },
	{ id: "Hungarian", label: "Hungarian" },
	{ id: "Icelandic", label: "Icelandic" },
	{ id: "Indonesian", label: "Indonesian" },
	{ id: "Iranian", label: "Iranian" },
	{ id: "Iraqi", label: "Iraqi" },
	{ id: "Irish", label: "Irish" },
	{ id: "Israeli", label: "Israeli" },
	{ id: "Italian", label: "Italian" },
	{ id: "Ivorian", label: "Ivorian" },
	{ id: "Jamaican", label: "Jamaican" },
	{ id: "Japanese", label: "Japanese" },
	{ id: "Jordanian", label: "Jordanian" },
	{ id: "Kazakhstani", label: "Kazakhstani" },
	{ id: "Kenyan", label: "Kenyan" },
	{ id: "Kiribati", label: "Kiribati" },
	{ id: "Korean", label: "Korean" },
	{ id: "Kuwaiti", label: "Kuwaiti" },
	{ id: "Kyrgyz", label: "Kyrgyz" },
	{ id: "Laotian", label: "Laotian" },
	{ id: "Latvian", label: "Latvian" },
	{ id: "Lebanese", label: "Lebanese" },
	{ id: "Liberian", label: "Liberian" },
	{ id: "Libyan", label: "Libyan" },
	{ id: "Liechtensteiner", label: "Liechtensteiner" },
	{ id: "Lithuanian", label: "Lithuanian" },
	{ id: "Luxembourgish", label: "Luxembourgish" },
	{ id: "Macedonian", label: "Macedonian" },
	{ id: "Malagasy", label: "Malagasy" },
	{ id: "Malawian", label: "Malawian" },
	{ id: "Malaysian", label: "Malaysian" },
	{ id: "Maldivian", label: "Maldivian" },
	{ id: "Malian", label: "Malian" },
	{ id: "Maltese", label: "Maltese" },
	{ id: "Marshallese", label: "Marshallese" },
	{ id: "Mauritanian", label: "Mauritanian" },
	{ id: "Mauritian", label: "Mauritian" },
	{ id: "Mexican", label: "Mexican" },
	{ id: "Micronesian", label: "Micronesian" },
	{ id: "Moldovan", label: "Moldovan" },
	{ id: "Monacan", label: "Monacan" },
	{ id: "Mongolian", label: "Mongolian" },
	{ id: "Moroccan", label: "Moroccan" },
	{ id: "Mozambican", label: "Mozambican" },
	{ id: "Namibian", label: "Namibian" },
	{ id: "Nauruan", label: "Nauruan" },
	{ id: "Nepalese", label: "Nepalese" },
	{ id: "New Zealand", label: "New Zealand" },
	{ id: "Nicaraguan", label: "Nicaraguan" },
	{ id: "Nigerian", label: "Nigerian" },
	{ id: "Nigerien", label: "Nigerien" },
	{ id: "Norwegian", label: "Norwegian" },
	{ id: "Omani", label: "Omani" },
	{ id: "Pakistani", label: "Pakistani" },
	{ id: "Palauan", label: "Palauan" },
	{ id: "Panamanian", label: "Panamanian" },
	{ id: "Papua New Guinean", label: "Papua New Guinean" },
	{ id: "Paraguayan", label: "Paraguayan" },
	{ id: "Peruvian", label: "Peruvian" },
	{ id: "Polish", label: "Polish" },
	{ id: "Portuguese", label: "Portuguese" },
	{ id: "Qatari", label: "Qatari" },
	{ id: "Romanian", label: "Romanian" },
	{ id: "Russian", label: "Russian" },
	{ id: "Rwandan", label: "Rwandan" },
	{ id: "Saint Lucian", label: "Saint Lucian" },
	{ id: "Salvadoran", label: "Salvadoran" },
	{ id: "Samoan", label: "Samoan" },
	{ id: "San Marinese", label: "San Marinese" },
	{ id: "Sao Tomean", label: "Sao Tomean" },
	{ id: "Saudi", label: "Saudi" },
	{ id: "Senegalese", label: "Senegalese" },
	{ id: "Serbian", label: "Serbian" },
	{ id: "Seychellois", label: "Seychellois" },
	{ id: "Sierra Leonean", label: "Sierra Leonean" },
	{ id: "Singaporean", label: "Singaporean" },
	{ id: "Slovak", label: "Slovak" },
	{ id: "Slovenian", label: "Slovenian" },
	{ id: "Solomon Islander", label: "Solomon Islander" },
	{ id: "Somali", label: "Somali" },
	{ id: "South African", label: "South African" },
	{ id: "Spanish", label: "Spanish" },
	{ id: "Sri Lankan", label: "Sri Lankan" },
	{ id: "Sudanese", label: "Sudanese" },
	{ id: "Surinamese", label: "Surinamese" },
	{ id: "Swazi", label: "Swazi" },
	{ id: "Swedish", label: "Swedish" },
	{ id: "Swiss", label: "Swiss" },
	{ id: "Syrian", label: "Syrian" },
	{ id: "Taiwanese", label: "Taiwanese" },
	{ id: "Tajik", label: "Tajik" },
	{ id: "Tanzanian", label: "Tanzanian" },
	{ id: "Thai", label: "Thai" },
	{ id: "Togolese", label: "Togolese" },
	{ id: "Tongan", label: "Tongan" },
	{ id: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
	{ id: "Tunisian", label: "Tunisian" },
	{ id: "Turkish", label: "Turkish" },
	{ id: "Tuvaluan", label: "Tuvaluan" },
	{ id: "Ugandan", label: "Ugandan" },
	{ id: "Ukrainian", label: "Ukrainian" },
	{ id: "Uruguayan", label: "Uruguayan" },
	{ id: "Uzbekistani", label: "Uzbekistani" },
	{ id: "Venezuelan", label: "Venezuelan" },
	{ id: "Vietnamese", label: "Vietnamese" },
	{ id: "Welsh", label: "Welsh" },
	{ id: "Yemeni", label: "Yemeni" },
	{ id: "Zambian", label: "Zambian" },
	{ id: "Zimbabwean", label: "Zimbabwean" }
  ];